fix race condition in test for abort() method
This failed on a test run: https://github.com/muxinc/upchunk/pull/49/checks?check_run_id=1957508634

This commit doesn't fix the race condition, but it makes it less likely
to happen :/ not ideal, but we'll go with it

```
* FAIL src/upchunk.spec.ts
  ● Console

    console.error
      Error: Uncaught [Error: expect(received).toBeTruthy()

      Received: false]
          at reportException (/home/runner/work/upchunk/upchunk/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
          at Timeout.task [as _onTimeout] (/home/runner/work/upchunk/upchunk/node_modules/jsdom/lib/jsdom/browser/Window.js:396:9)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7) JestAssertionError: expect(received).toBeTruthy()

      Received: false
          at /home/runner/work/upchunk/upchunk/src/upchunk.spec.ts:315:30
          at Timeout.task [as _onTimeout] (/home/runner/work/upchunk/upchunk/node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7) {
        matcherResult: { message: [Function: message], pass: false }
      }

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:28)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:396:9)
```